if (typeof ncbi === "undefined") {
    ncbi = {};
}

ncbi.sgAppsWithScrolling = [
    {"ncbi_app": "entrez",
     "ncbi_db": "gene",
     "ncbi_report": "full_report"},
     {"foo": "bar"}
];

;
(function(){function L(a){return ncbi.sg._urls.getAttrFromStr("jsevent",a)}function M(a){for(var b=ncbi.sg.reservedParams,c=0;c<b.length;c++)if(a==b[c])return true;return false}function N(a,b){b=ncbi.sg._urls.getDataObj(b);var c={},f=ncbi.sg.pingCallbacks;a=typeof f[a]!=="undefined"?f[a]:[];for(f=0;f<a.length;f++)ncbi.sg._urls.addDataToObj(c,a[f](b));for(var g in c)if(M(g)){delete c[g];console.warn("You tried to add param '"+g+"' to ping data, but that parameter is reserved.")}return c}if(typeof ncbi===
"undefined")ncbi={};if(ncbi.sg)typeof console!=="undefined"&&console.warn&&console.warn("The logging JavaScript was added twice in the document. Please include it once.");else{ncbi.sg=function(){};ncbi.sg.getInstance=function(){if(!ncbi.sg._instance)ncbi.sg._instance=new ncbi.sg;return ncbi.sg._instance};ncbi.sg._instance=null;ncbi.sg._version="37";(function(){var a=navigator.cookieEnabled?true:false;if(typeof navigator.cookieEnabled==="undefined"&&!a){document.cookie="testcookie";a=document.cookie.indexOf("testcookie")!==
-1?true:false}ncbi.sg.isCookieEnabled=a;ncbi.sg.isClickingEnabled=typeof __ncbi_sg_isClickingEnabled==="undefined"?true:!!__ncbi_sg_isClickingEnabled;ncbi.sg.calcXY=typeof __ncbi_sg_calcXY==="undefined"?true:!!__ncbi_sg_calcXY;a={};for(var b in window){var c=b.match(/^__ncbi_sg_pingCallbacks_(\w+)_(.+)$/);if(c&&typeof c[1]!=="undefined"){c=c[1];var f=window[b];a[c]=a[c]||[];a[c].push(f)}}ncbi.sg.pingCallbacks=a})();ncbi.sg.appLogIgnore=["ncbi_sessionid","ncbi_clickdisabled"];ncbi.sg.reservedParams=
["jsevent","sgSource","sgVersion","hasScrolled","jseventms","ncbi_phid","ncbi_timeonpage","ncbi_timesinceload"];ncbi.sg.prototype={init:function(){this.isProcessRunning=true;this._setUpMetaTagValues();this._setScrollingEnabled();if(this._cachedVals.ncbi_db&&this._cachedVals.ncbi_db.value.toLowerCase()=="pubmed"&&this._cachedVals.ncbi_report&&this._cachedVals.ncbi_report.value.toLowerCase()=="abstract"&&this._cachedVals.ncbi_resultcount&&this._cachedVals.ncbi_resultcount.value.toLowerCase()=="1"||
this._cachedVals.ncbi_db&&this._cachedVals.ncbi_db.value.toLowerCase()=="pmc"&&this._cachedVals.ncbi_report&&this._cachedVals.ncbi_report.value.toLowerCase()=="record"&&this._cachedVals.ncbi_type&&this._cachedVals.ncbi_type.value.toLowerCase()=="fulltext")ncbi.sg.isHoverEnabled=true;this._setUpPathParts();this._setUpCustomProps();this._addOnScrollListeners();this._send("init");this._scheduleDOMReadyPing();this._sendPrev();this._addPrintPing();ncbi.sg.isScrollingEnabled&&this._setBeforeScrollDetails()},
_vals:{},_cachedVals:{},_hasInitRun:false,_readyPinged:false,_linkObjs:[],_pathParts:{part1:"",part2:"",part3:"",part4:""},_scheduleDOMReadyPing:function(){var a=this,b=function(){return typeof jQuery!=="undefined"&&typeof jQuery.ui!=="undefined"&&typeof jQuery.ui.jig!=="undefined"?typeof jQuery.ui.jig.version!=="undefined"&&jQuery.ui.jig.version?jQuery.ui.jig.version:"unknown":"unknown"},c=function(){var n={},m=jQuery.ui.jig._foundWidgets;for(var v in m)n["jigWidget_"+v]=m[v];n.jigVersion=b();return n},
f=function(n){var m=ncbi.sg.getInstance();m.storeAllHeadings();for(var v=m.getVisibleHeadingIDs(),F=[],x=0;x<v.length;x++){var d=v[x];d&&F.push(encodeURIComponent(d))}m=m.getHiddenHeadingIDs();var e=[];for(x=0;x<m.length;x++)(d=m[x])&&e.push(encodeURIComponent(d));n["visible.headingIDs"]=F.join(",");n["numVisible.headingIDs"]=v.length;n["hidden.headingIDs"]=e.join(",");n["numHidden.headingIDs"]=m.length},g=function(){if(!a._readyPinged){var n={};if(typeof jQuery!=="undefined"&&typeof jQuery.ui!==
"undefined"&&typeof jQuery.ui.jig!=="undefined"&&typeof jQuery.ui.jig.scanned!=="undefined")if(jQuery.ui.jig.scanned){n=c();n.jsevent="domready";ncbi.sg.isScrollingEnabled&&f(n);ncbi.sg._ping(n);a._readyPinged=true}else{if(typeof jQuery.ui.jig.scan!=="undefined"&&jQuery.ui.jig.scan){var m=jQuery.ui.jig.scan;jQuery.ui.jig.scan=function(){var v=m.apply(this,arguments);g();return v}}}else{n.jigVersion="nojig";n.jsevent="domready";ncbi.sg.isScrollingEnabled&&f(n);ncbi.sg._ping(n);a._readyPinged=true}}};
if(document.addEventListener){var i=function(){document.removeEventListener("DOMContentLoaded",i,false);g()};document.addEventListener("DOMContentLoaded",i)}else if(document.attachEvent){var p=function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",p);g()}};document.attachEvent("onreadystatechange",p)}},_setScrollingEnabled:function(){try{ncbi.sg.isScrollingEnabled=false;var a=ncbi.sgAppsWithScrolling;if(typeof a!=="undefined")for(var b=0;b<a.length;b++){var c=true,
f=a[b];for(var g in f)if(!this._cachedVals[g]||this._cachedVals[g].value.toLowerCase()!=f[g]){c=false;break}if(c){ncbi.sg.isScrollingEnabled=true;break}}}catch(i){ncbi.sg.getInstance().noteEventData("jserror",{jserror:i.toString(),SELF_URL:window.location.href},["ncbi_sessionid","ncbi_phid"])}},_setUpMetaTagValues:function(){for(var a=document.getElementsByTagName("meta"),b=0;b<a.length;b++){var c=a[b].name;c.indexOf("ncbi_")===0&&this.addEntry(c,a[b].content)}},_setUpCachedMetaTagValues:function(a){for(var b=
0;b<a.length;b++){var c=this._cachedVals[a[b]];c&&this.addEntry(a[b],c.value)}},cachedNames:["ncbi_app","ncbi_db","ncbi_pcid","ncbi_pdid","ncbi_phid","ncbi_sessionid","ncbi_uidlist"],ignoreLengthRestrictions:["jserror","jserrorlocation"],addEntry:function(a,b){if(!(b===undefined||b.length===0)){if(b.length>100&&this.ignoreLengthRestrictions.indexOf(a)===-1)b=b.substr(0,100);this._cachedVals[a]={sProp:a,value:b}}},getVal:function(a){return typeof this._cachedVals[a]!=="undefined"&&this._cachedVals[a]&&
typeof this._cachedVals[a].value!=="undefined"?this._cachedVals[a].value:null},removeAllEntries:function(){for(var a={},b=this.cachedNames.length,c=0;c<b;c++){var f=this.cachedNames[c],g=this._cachedVals[f];if(g)a[f]=g}this._cachedVals=a;for(var i in this._pathParts)this._pathParts[i]=""},_setUpCustomProps:function(){var a=this._pathParts.part1,b=this._pathParts.part2.length>0?":"+this._pathParts.part2:"",c=this._pathParts.part3.length>0?":"+this._pathParts.part3:"",f=this._pathParts.part4.length>
0?":"+this._pathParts.part4:"";a={pagename:a+b+c,server:window.location.hostname,sitesect2:a+b,subsect3:a+b+c,subsect4:a+b+c+f,heir1:(a+b+c+f).replace(/:/g,"|")};for(var g in a)this.addEntry(g,a[g]);this._sessionIdCheck();this._staticPageCheck();this._prevHitCheck();this._browserConfigurationSettings();this._hashCheck()},_staticPageCheck:function(){this._cachedVals.ncbi_app&&this._cachedVals.ncbi_app.value.length>0||this.addEntry("ncbi_app","static");this._cachedVals.ncbi_pdid&&this._cachedVals.ncbi_pdid.value.length>
0||this.addEntry("ncbi_pdid",(document.title||"unknown").replace(/\s+/g,""))},_sessionIdCheck:function(){if(!(this._cachedVals.ncbi_sessionid&&this._cachedVals.ncbi_sessionid.value.length>0)){var a="";if(a.length===0){var b=this.getCookie("ncbi_sid");if(b.length>0)a=b}if(a.length===0){b=this.getCookie("WebCubbyUser")||this.getCookie("WebEnv");if(b.length>0){b=unescape(b).split("@");if(b.length>1)a=b[b.length-1]}}if(a.length===0)a="UNK_SESSION";this.addEntry("ncbi_sessionid",a)}},getBrowserWidthHeight:function(){var a=
this.getViewportWidth(),b=this.getViewportHeight();return{width:a,height:b}},_browserConfigurationSettings:function(){if(ncbi.sg.calcXY){var a=this.getBrowserWidthHeight();this.addEntry("browserwidth",a.width);this.addEntry("browserheight",a.height);this.addEntry("screenwidth",screen.width);this.addEntry("screenheight",screen.height);this.addEntry("screenavailwidth",screen.availWidth);this.addEntry("screenavailheight",screen.availHeight);if(document&&document.body){var b=document.body.scrollWidth,
c=document.body.scrollHeight,f=c>a.height?"true":"false";this.addEntry("canscroll_x",b>a.width?"true":"false");this.addEntry("canscroll_y",f);this.addEntry("scrollwidth",b);this.addEntry("scrollheight",c)}}if(screen.colorDepth)this.addEntry("colorDepth",screen.colorDepth);else screen.pixelDepth&&this.addEntry("colorDepth",screen.pixelDepth)},_hashCheck:function(){var a=window.location.hash;if(a){a=a.replace("#","");this.addEntry("urlhash",a)}(a=window.location.search.match(/[?&]campaign=([^&]*)/))&&
this.addEntry("campaign",a[1])},_createPHID:function(){var a=this._cachedVals.ncbi_sessionid.value,b=a.substr(0,15)+"9"+(new Date).getTime().toString(),c=a.length;b+=a.substr(c-(32-b.length),c);a={value:b};this.addEntry("ncbi_phid",b);return a},currentPageHitId:null,currentPHIDMatchesPrev:false,_prevHitCheck:function(){var a=this.getCookie("ncbi_prevPHID"),b=this._cachedVals.ncbi_phid;a.length>0&&this.addEntry("prev_phid",a);if(!b||!b.value||b.value.length===0)b=this._createPHID();if(b.value==a)this.currentPHIDMatchesPrev=
true;this.currentPageHitId=b.value;var c=this;ncbi.sg._hasFocus&&c.setCookie("ncbi_prevPHID",b.value);var f=window.onfocus;window.onfocus=function(g){c.getCookie("ncbi_prevPHID")!==b.value&&c.setCookie("ncbi_prevPHID",b.value);typeof f==="function"&&f(g)}},_setUpPathParts:function(){var a=this._cachedVals.ncbi_app,b=this._cachedVals.ncbi_db,c=this._cachedVals.ncbi_pdid,f=this._cachedVals.ncbi_pcid;this._pathParts.part1=a!==undefined?a.value:"";this._pathParts.part2=b!==undefined?b.value:"";this._pathParts.part3=
c!==undefined?c.value:"";this._pathParts.part4=f!==undefined?f.value:""},getPerfStats:function(){var a=window.performance;if(!a)return{};var b=a.timing;if(b)b={dns:b.domainLookupEnd-b.domainLookupStart,connect:b.connectEnd-b.connectStart,ttfb:b.responseStart-b.connectEnd,basePage:b.responseEnd-b.responseStart,frontEnd:b.loadEventStart-b.responseEnd};else return{};if(a=a.navigation){b.navType=a.type;b.redirectCount=a.redirectCount}return b},setPerfStats:function(a,b){var c=this.getPerfStats();for(var f in c){var g=
c[f];if(g>=0){var i="jsperf_"+f;if(b)a[i]=g;else a.push(i+"="+g)}}},getExtraRenderStats:function(){var a={SELF_URL:encodeURIComponent(window.location.href)};if(typeof document!=="undefined"&&typeof document.referrer!=="undefined")a.HTTP_REFERER=encodeURIComponent(document.referrer);return a},setExtraRenderStats:function(a){var b=this.getExtraRenderStats();for(var c in b)a.push(c+"="+b[c])},_send:function(a,b,c){if(typeof c==="undefined"||c===null)c=true;var f=[];if(a==="init"){f.push("jsevent=render");
ncbi.sg.renderTime=new Date;if(typeof ncbi_startTime!=="undefined"){f.push("jsrendertime="+(ncbi.sg.renderTime-ncbi_startTime));ncbi.sg.loadTime&&f.push("jsloadtime="+(ncbi.sg.loadTime-ncbi_startTime))}this.setPerfStats(f);this.setExtraRenderStats(f);f.push("cookieenabled="+(ncbi.sg.isCookieEnabled?"true":"false"))}for(var g in this._cachedVals)ncbi.sg.appLogIgnore.indexOf(g)===-1&&f.push(g+"="+encodeURIComponent(this._cachedVals[g].value));this._sendAl(f.join("&"),b,true,c);this._hasInitRun=true;
var i=this;setTimeout(function(){i.isProcessRunning=false;i.runSGProcess()},300)},send:function(a,b){this._send(a,b,false)},_sendPrev:function(){var a=ncbi.sg.getInstance(),b;b=a.getCookie("prevselfurl")!=document.referrer?"false":"true";a.getCookie("ncbi_prevPHID");var c=a.getCookie("clicknext");if(c){if(!a.currentPHIDMatchesPrev){c=ncbi.sg._urls.addAttrToStr("directnav",b,c);ncbi.sg._ping(c)}a.setCookie("clicknext","")}if(c=a.getCookie("prevsearch")){if(!a.currentPHIDMatchesPrev){c=ncbi.sg._urls.addAttrToStr("directnav",
b,c);ncbi.sg._ping(c)}a.setCookie("prevsearch","")}if(c=a.getCookie("unloadnext")){if(!a.currentPHIDMatchesPrev){c=ncbi.sg._urls.addAttrToStr("directnav",b,c);ncbi.sg._ping(c)}a.setCookie("unloadnext","")}a.setCookie("prevselfurl","")},_sendAl:function(a,b,c,f){if(typeof f==="undefined"||f===null)f=true;var g=L(a);g=N(g,a);if(a.indexOf("jseventms")===-1)a+="&jseventms="+ncbi.sg.getInstance().getMillisecondsSinceSunday();if(a.match(/jsevent=search/i)){for(var i=ncbi.sg.addTimeonpageToAr([]),p=0;p<
i.length;p++)a+="&"+i[p];a.match(/jsevent=searchnext/i)||(a+="&eventid="+ncbi.sg.getEventId());i=a.replace(/jsevent=search(next)?/i,"jsevent=searchnext");this.setCookie("prevselfurl",window.location.href,null);this._storeNext("prevsearch",i,null,f)}a+="&sgVersion="+ncbi.sg._version;if(a.indexOf("sgSource")===-1)a=this._setSgSource(a,f);a=ncbi.sg._urls.addDataToStr(g,a);reqURL=ncbi.sg.getStatUrl(a);this.makeRequest(reqURL,function(){typeof b==="function"&&b()},c)},makeRequest:function(a,b,c){typeof ncbi_pingWithImage!==
"undefined"&&ncbi_pingWithImage?this.makeImgRequest(reqURL,function(){typeof callbackFnc==="function"&&callbackFnc()},c):this.makeAjaxCall(reqURL,function(){typeof callbackFnc==="function"&&callbackFnc()},c);this._pushPingFired(a)},sendAl:function(a,b,c){this._sendAl(a,b,c,false)},_processingQueue:[],isProcessRunning:false,addSGProcess:function(a){this._processingQueue.push(a)},getSGProcess:function(a){return this._processingQueue.shift(a)},runSGProcess:function(){if(this.isProcessRunning||this._processingQueue.length===
0||!this._hasInitRun)return false;this.isProcessRunning=true;this.removeAllEntries();var a=this.getSGProcess();this._setUpCachedMetaTagValues(a.metadata);this.addEntry("jsevent",a.eventName);for(var b in a.props)this.addEntry(b,a.props[b]);this._send(a.eventName,a.callbackFnc);var c=this;setTimeout(function(){c.isProcessRunning=false;c.runSGProcess()},300)},noteEventData:function(a,b,c,f){this.addSGProcess({eventName:a,props:b,metadata:c,callback:f});this.runSGProcess()},setCookie:function(a,b,c){if(window.sessionStorage)try{sessionStorage.setItem(a,
b)}catch(f){}var g=new Date;c!==null&&g.setDate(g.getDate()+c);document.cookie=a+"="+escape(b)+(c===null?"":"; expires="+g.toGMTString())+"; domain="+escape(".ncbi.nlm.nih.gov")+"; path=/"},_setSgSource:function(a,b){a+="&sgSource="+(b?"native":"api");return a},_storeNext:function(a,b,c,f){if(typeof f==="undefined"||f===null)f=true;b=this._setSgSource(b,f);this.setCookie(a,b,c)},getCookie:function(a){var b;if(window.sessionStorage){try{b=sessionStorage.getItem(a)||""}catch(c){b=""}if(b.length>0)return b}if(document.cookie.length>
0){b=document.cookie.indexOf(a+"=");if(b!==-1){b=b+a.length+1;a=document.cookie.indexOf(";",b);if(a===-1)a=document.cookie.length;return unescape(document.cookie.substring(b,a))}}return""},getTransport:function(){var a=null;if(window.XMLHttpRequest)try{a=new XMLHttpRequest;this.getTransport=function(){return new XMLHttpRequest}}catch(b){a=null}if(window.ActiveXObject&&a===null)try{a=new ActiveXObject("Msxml2.XMLHTTP");this.getTransport=function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(c){try{a=
new ActiveXObject("Microsoft.XMLHTTP");this.getTransport=function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(f){a=false}}if(a===null)this.getTransport=function(){return null};return this.getTransport()},_shouldStorePing:function(a){return a.search(/jsevent=(click|search|unload)next/)!==-1||(a.search("jsevent=render")!==-1||a.search("jsevent=domready")!==-1||a.search("jsevent=jserror")!==-1)&&a.search("sgSource=api")===-1},_pushPingFired:function(a){this._shouldStorePing(a)&&ncbi.sg.pingsFired.push(a)},
_pushPingSucceeded:function(a){this._shouldStorePing(a)&&ncbi.sg.pingsSucceeded.push(a)},makeAjaxCall:function(a,b,c){var f=this,g=this.getTransport();g._ncbi_skipOverride=true;g.open("GET",a,c);if(c)g.onreadystatechange=function(){if(g.readyState===4){ncbi.sg.outstandingPings-=1;f._pushPingSucceeded(a);b(g)}};ncbi.sg.lastPing=g;ncbi.sg.outstandingPings+=1;g.send(null);return g},makeImgRequest:function(a,b){var c=this,f=document.createElement("img");f.setAttribute("src",a);f.style.display="none";
f.onload=function(){if(!this.complete||typeof this.naturalWidth==="undefined"||this.naturalWidth==0)console.warn("could not load stat img");else{c._pushPingSucceeded(a);b()}ncbi.sg.outstandingPings-=1;document.body.removeChild(f)};ncbi.sg.outstandingPings+=1;document.body.appendChild(f)},scrollDetails:{maxScroll_x:0,maxScroll_y:0,currScroll_x:0,currScroll_y:0,hasScrolled:false},scrollEventDetails:{xTenths:0,yTenths:0,xMax:0,yMax:0},_visibleHeadings:[],_hiddenHeadings:[],_getScrollXYPx:function(){return[window.pageXOffset||
document.documentElement.scrollLeft||document.body.scrollLeft||0,window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0]},_getScrollXY:function(){var a=this.getViewportHeight(),b=this.getViewportWidth(),c=document.body.scrollHeight,f=document.body.scrollWidth,g=this._getScrollXYPx(),i=Math.round(g[1]/a*10)/10;return{xRel:Math.round(g[0]/b*10)/10,yRel:i,viewportHeight:a,viewportWidth:b,pageHeight:c,pageWidth:f}},_addOnScrollListeners:function(){var a=window.onscroll,b=this;
window.onscroll=function(){if(ncbi.sg.isScrollingEnabled){b._setScrollDetails();b.scrollDetails.hasScrolled=true;b._addScrollEvent()}else{b._setScrollDetails();b.scrollDetails.hasScrolled=true}if(typeof a==="function")return a()}},getViewportHeight:function(){return window.innerHeight?window.innerHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body!==null?document.body.clientHeight:"NA"},getViewportWidth:function(){return window.innerWidth?
window.innerWidth:document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:document.body!==null?document.body.clientWidth:"NA"},_setScrollDetails:function(){if(ncbi.sg.calcXY){this.scrollDetails.currScroll_y=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0;this.scrollDetails.currScroll_x=window.pageXOffset||document.documentElement.scrollLeft||document.body.scrollLeft||0;this.getViewportWidth();this.getViewportHeight();if(this.scrollDetails.maxScroll_y<
this.scrollDetails.currScroll_y)this.scrollDetails.maxScroll_y=this.scrollDetails.currScroll_y;if(this.scrollDetails.maxScroll_x<this.scrollDetails.currScroll_x)this.scrollDetails.maxScroll_x=this.scrollDetails.currScroll_x}},isVisible:function(a){var b=this.findEffectiveStyleProperty(a,"visibility");a=this._isDisplayed(a);return b!="hidden"&&a},_isDisplayed:function(a){if(this.findEffectiveStyleProperty(a,"display")=="none")return false;if(a.parentNode.style)return this._isDisplayed(a.parentNode);
return true},findEffectiveStyleProperty:function(a,b){var c=this.findEffectiveStyle(a)[b];if(c=="inherit"&&a.parentNode.style)return this.findEffectiveStyleProperty(a.parentNode,b);return c},findEffectiveStyle:function(a){if(a.style!=undefined){if(window.getComputedStyle)return window.getComputedStyle(a,null);if(a.currentStyle)return a.currentStyle;if(window.document.defaultView&&window.document.defaultView.getComputedStyle)return window.document.defaultView.getComputedStyle(a,null);return null}},
findElementPos:function(a,b,c){var f=0,g=0;if(a.offsetLeft)f+=parseInt(a.offsetLeft);if(a.offsetTop)g+=parseInt(a.offsetTop);if(a.scrollTop&&a.scrollTop>0){g-=parseInt(a.scrollTop);c=true}if(a.scrollLeft&&a.scrollLeft>0){f-=parseInt(a.scrollLeft);b=true}if(a.offsetParent){b=this.findElementPos(a.offsetParent,b,c);if(b==-1)return-1;f+=b[0];g+=b[1]}else if(a.ownerDocument){var i=a.ownerDocument.defaultView;if(!i&&a.ownerDocument.parentWindow)i=a.ownerDocument.parentWindow;if(i){var p=i.pageXOffset!==
undefined?i.pageXOffset:(a.document.documentElement||a.document.body.parentNode||a.document.body).scrollLeft;a=i.pageYOffset!==undefined?i.pageYOffset:(a.document.documentElement||a.document.body.parentNode||a.document.body).scrollTop;if(!c&&a&&a>0)g-=parseInt(a);if(!b&&p&&p>0)f-=parseInt(p)}}return[f,g]},getJoinedData:function(a){var b=[];for(var c in a)b.push(c+"="+encodeURIComponent(a[c]));return b.join("&")},addScrollHeadingData:function(a,b){var c=this.scrollEventDetails.headings;if(c){a["numHeadings."+
this._scrollOrder+".scrollInfo"]=c.length;for(var f=0;f<c.length;f++){var g=c[f];if(g.visible){var i={};if(g.innerText)i["innerText."+g.index+".headings."+this._scrollOrder+".scrollInfo"]=g.innerText;if(g.id)i["id."+g.index+".headings."+this._scrollOrder+".scrollInfo"]=g.id;i["tagName."+g.index+".headings."+this._scrollOrder+".scrollInfo"]=g.tagName;b=b?b:1800;this.getJoinedData(a).length+this.getJoinedData(i).length<b&&ncbi.sg._urls.addDataToObj(a,i)}}}return a},storeAllHeadings:function(){for(var a=
[],b=[],c=document.getElementsByTagName("*"),f=-1,g=0;g<c.length;g++){for(var i=c[g],p=false,n=i.tagName.toLowerCase(),m=0;m<7;m++)if(n=="h"+m)p=true;if(p){f+=1;m=this.findElementPos(i);p=m[1];m=m[0];var v=i.offsetHeight,F=i.offsetWidth,x=this.getViewportHeight(),d=this.getViewportWidth(),e={},h=i.getAttribute("id")||i.id;if(h)e.id=h;if(h=(i.getAttribute("innerText")||i.innerText||i.getAttribute("textContent")||i.textContent||"").replace(/^\s+|\s+$/g,""))e.innerText=h.substring(0,50);e.index=f;e.tagName=
n;n=false;if(p+v>=0&&p<=x&&m+F>=0&&m<=d)if(this.isVisible(i))n=true;(e.visible=n)?a.push(e):b.push(e)}}this._visibleHeadings=a;this._hiddenHeadings=b},getVisibleHeadings:function(){return this._visibleHeadings},getHiddenHeadings:function(){return this._hiddenHeadings},getVisibleHeadingIDs:function(){for(var a=this.getVisibleHeadings(),b=[],c=0;c<a.length;c++)b.push(a[c].id);return b},getHiddenHeadingIDs:function(){for(var a=this.getHiddenHeadings(),b=[],c=0;c<a.length;c++)b.push(a[c].id);return b},
_setBeforeScrollDetails:function(a){this._lastScroll=a?a:null;if(ncbi.sg.calcXY){a=this._getScrollXY();var b=a.yRel;this.scrollEventDetails.xTenths=Math.round(a.xRel*10);this.scrollEventDetails.yTenths=Math.round(b*10);this.scrollEventDetails.xMax=Math.max(this.scrollEventDetails.xTenths,this.scrollEventDetails.xMax);this.scrollEventDetails.yMax=Math.max(this.scrollEventDetails.yTenths,this.scrollEventDetails.yMax)}this.storeAllHeadings();this.scrollEventDetails.headings=this.getVisibleHeadings()},
getScrollDetails:function(a,b){if(!ncbi.sg.isScrollingEnabled)if(ncbi.sg.calcXY){this._setScrollDetails();return this.scrollDetails}else return{};var c=this.scrollEventDetails;c.tstamp=(new Date).getTime();var f=this._getScrollXY(),g=null;if(b||!this._lastScroll||c.tstamp-this._lastScroll>1E3){this._scrollOrder=this._scrollOrder!=undefined?this._scrollOrder+1:0;if(ncbi.sg.calcXY)var i="yTenths."+this._scrollOrder+".scrollInfo",p="xTenths."+this._scrollOrder+".scrollInfo",n="maxXTenths."+this._scrollOrder+
".scrollInfo",m="maxYTenths."+this._scrollOrder+".scrollInfo";b={};b["duration."+this._scrollOrder+".scrollInfo"]=this._lastScroll?c.tstamp-this._lastScroll:new Date-ncbi.sg.loadTime;if(ncbi.sg.calcXY){b[p]=this.scrollEventDetails.xTenths;b[i]=this.scrollEventDetails.yTenths;b[n]=this.scrollEventDetails.xMax;b[m]=this.scrollEventDetails.yMax;b["viewportHeight."+this._scrollOrder+".scrollInfo"]=f.viewportHeight;b["viewportWidth."+this._scrollOrder+".scrollInfo"]=f.viewportWidth;b["maxPossibleScrollTenthsY."+
this._scrollOrder+".scrollInfo"]=Math.round((f.pageHeight/f.viewportHeight-1)*10);b["maxPossibleScrollTenthsX."+this._scrollOrder+".scrollInfo"]=Math.round((f.pageWidth/f.viewportWidth-1)*10)}g=b=this.addScrollHeadingData(b,a)}this._setBeforeScrollDetails(c.tstamp);return g},getScrollDetailsAr:function(a,b){var c=[];a=this.getScrollDetails(a,b);for(var f in a)c.push(f+"="+encodeURIComponent(a[f]));return c},addScrollDetailsAr:function(a,b,c){b=this.getScrollDetailsAr(b,c);for(c=0;c<b.length;c++)a.push(b[c])},
addScrollDetails:function(a,b,c){b=this.getScrollDetails(b,c);for(var f in b)a[f]=b[f]},_addScrollEvent:function(){try{var a=this.getScrollDetails();if(a){a.jsevent="scroll";ncbi.sg._ping(a)}}catch(b){ncbi.sg.getInstance().noteEventData("jserror",{jserror:b.toString(),SELF_URL:window.location.href},["ncbi_sessionid","ncbi_phid"])}},_addPrintPing:function(){function a(){var f=document.createElement("style");f.type="text/css";var g=document.createElement("style");g.type="text/css";g.media="print";for(var i=
["jsevent=print"],p=0;p<b.cachedNames.length;p++){var n=b.cachedNames[p],m=b._cachedVals[n];m&&n!=="ncbi_sessionid"&&i.push(n+"="+encodeURIComponent(m.value))}i=".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }.print-log li { list-style-image: url('"+ncbi.sg.getStatUrl(i.join("&"))+"'); }";if(g.styleSheet){g.styleSheet.cssText=i;f.styleSheet.cssText=".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }"}else{g.appendChild(document.createTextNode(i));
f.appendChild(document.createTextNode(".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }"))}i=document.getElementsByTagName("head")[0];i.appendChild(g);i.appendChild(f);f=document.createElement("ul");f.className="print-log";g=document.createElement("li");f.appendChild(g);document.body.appendChild(f)}var b=this;if(typeof jQuery!=="undefined")jQuery(a);else{var c=window.onload;window.onload=function(f){c&&c(f);a()}}},getMillisecondsSinceSunday:function(){var a=
new Date,b=new Date;b.setDate(b.getDate()-b.getDay());b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);return(a-b).toString(36)},addLinkObjs:function(a){this._linkObjs.push(a)},isInLinkObjs:function(a){for(var b=this._linkObjs,c=0;c<b.length;c++)for(var f=b[c],g=0;g<f.length;g++)if(a==f[g])return true;return false}};ncbi.sg.lastPing=null;ncbi.sg.hasNotedErrorEvent=false;ncbi.sg.getTimeonpageData=function(){var a={};if(typeof ncbi_startTime!=="undefined"){a.ncbi_timeonpage=new Date-
ncbi_startTime;if(typeof ncbi_onloadTime!=="undefined"&&ncbi_onloadTime)a.ncbi_onloadTime=ncbi_onloadTime-ncbi_startTime}return a};ncbi.sg.addTimeonpageDetails=function(a){var b=ncbi.sg.getTimeonpageData();for(var c in b)a[c]=b[c];return a};ncbi.sg.addTimeonpageToAr=function(a){var b=ncbi.sg.getTimeonpageData();for(var c in b)a.push(c+"="+b[c]);return a};ncbi.sg.getStatUrl=function(a){var b=window.location.port?":"+window.location.port:"";return typeof __ncbi_stat_url!=="undefined"?__ncbi_stat_url+
"?"+a:window.location.protocol+"//"+window.location.hostname+b+"/stat?"+a};(function(){function a(){ncbi.sg.getInstance().setCookie("ncbi_prevPHID",ncbi.sg.getInstance().currentPageHitId);if(m.length>0)for(;m.length>0;)c(m.pop());var d={jsevent:"unload",ncbi_pingaction:"unload"};d=ncbi.sg.addTimeonpageDetails(d);d.eventid=ncbi.sg.getEventId();var e=ncbi.sg.getInstance();e.setPerfStats(d,true);e.addScrollDetails(d,1800-e.getJoinedData(d).length,true);if(!x){ncbi.sg._ping(d);var h="";for(var k in d)h+=
k+"="+(k==="jsevent"?"unloadnext":d[k])+"&";h+="ncbi_phid="+e.currentPageHitId;e.setCookie("prevselfurl",window.location.href,null);e._storeNext("unloadnext",h,null)}x=true}function b(d){for(var e=m.length-1;e>=-1;e--)if(m[e]===d){m.slice(e,1);break}c(d)}function c(d,e){if(v.indexOf(d.tstamp)===-1){v.push(d.tstamp);F.push(d);f("click",d,e)}}function f(d,e,h,k){if(typeof k==="undefined"||k===null)k=true;var o=d==="click"?"link":"elem",l=e.link,s=e.evt,j=l.id||"",q=l.name||"",w=l.sid||"",z=l.href||
"",D=l.innerText||l.textContent||"";if(D.length>50)D=D.substr(0,50);var A=l.getAttribute?l.getAttribute("ref")||l.ref||"":"",G=l.className?l.className.replace(/^\s?/,"").replace(/\s?$/,"").split(/\s/g).join(",")||"":"";e=[];var I=[],y=l.parentNode;if(y)for(var t=0;t<6&&y!==null;t++){(parId=y.id)&&e.push(parId);if(parClassName=y.className)I=I.concat(parClassName.split(/\s/));y=y.parentNode}y=ncbi.sg.getInstance();t=y.currentPageHitId||"";var r=[];j.length>0&&r.push(o+"_id="+encodeURIComponent(j));
q.length>0&&r.push(o+"_name="+encodeURIComponent(q));w.length>0&&r.push(o+"_sid="+encodeURIComponent(w));z.length>0&&r.push(o+"_href="+encodeURIComponent(z));D.length>0&&r.push(o+"_text="+encodeURIComponent(D));G.length>0&&r.push(o+"_class="+encodeURIComponent(G));if(ncbi.sg.calcXY){t=y.getBrowserWidthHeight();t.width!==null&&r.push("browserwidth="+encodeURIComponent(t.width));t.height!==null&&r.push("browserheight="+encodeURIComponent(t.height))}for(var J in s){t=s[J];t!==undefined&&r.push(J.toLowerCase()+
"="+t.toString())}d==="click"&&r.push("eventid="+encodeURIComponent(ncbi.sg.getEventId()));r.push("jsevent="+d);A.length>0&&r.push(A);if(typeof jQuery!=="undefined")if(l=jQuery(l).attr("sg")){l=l.split(/\}\s*,\s*\{/);for(t=0;t<l.length;t++){s=l[t].match(/name\s*:\s*'(.+)',\s*selector\s*:\s*'(.+)'/);if(s.length===3){J="cust_"+s[1];s=jQuery(s[2]).val();r.push(J+"="+encodeURIComponent(s))}}}if(h&&h.length>0)for(;h.length>0;)r.push(h.shift());e.length>0&&r.push("ancestorId="+e.join(","));I.length>0&&
r.push("ancestorClassName="+I.join(",").replace(/\s+/g," ").replace(/(^\s|\s$)/g,""));y.addScrollDetailsAr(r,1800-r.join("&").length,true);if(d==="click"){r=ncbi.sg.addTimeonpageToAr(r);d=r.join("&").replace("jsevent=click","jsevent=clicknext");t=ncbi.sg.getInstance().currentPageHitId||"";d+="&ncbi_phid="+t;y.setCookie("prevselfurl",window.location.href,null);y._storeNext("clicknext",d,null,k)}ncbi.sg._ping(r,true,null,null,k)}function g(d){var e={};if(ncbi.sg.calcXY&&d){if(d.clientX||d.clientY){var h=
ncbi.sg.getInstance()._getScrollXYPx();e.evt_coor_x=d.clientX+h[0];e.evt_coor_y=d.clientY+h[1]}else if(d.pageX||d.pageY){e.evt_coor_x=d.pageX;e.evt_coor_y=d.pageY}e.jseventms=ncbi.sg.getInstance().getMillisecondsSinceSunday()}return e}function i(d,e,h,k,o){var l={},s=null,j=null;if(typeof e==="string"){s=e;j=h}else{l=g(e);s=h;j=k}if(j){e=typeof j;if(e==="string")j=[j];else if(e==="object"&&!(j instanceof Array)){e=[];for(var q in j)e.push(q+"="+j[q]);j=e}}f(s,{link:d,evt:l},j,o)}function p(d,e,h){var k=
[];if(typeof e==="undefined")e=true;if(typeof d==="object"&&!(d instanceof Array))for(var o in d)k.push(o+"="+encodeURIComponent(d[o]));else if(typeof d==="string")k.push(d);else k=d;d=ncbi.sg.getInstance().currentPageHitId||"";o=null;if(typeof ncbi.sg.loadTime!=="undefined")o=new Date-ncbi.sg.loadTime;var l=k.join("&");if(l.indexOf("jsevent=clicknext")!==-1||l.indexOf("jsevent=searchnext")!==-1||l.indexOf("jsevent=unloadnext")!==-1){d.length>0&&k.push("next_phid="+encodeURIComponent(d));o!==null&&
k.push("next_ncbi_timesinceload="+o)}else{d.length>0&&k.push("ncbi_phid="+encodeURIComponent(d));o!==null&&k.push("ncbi_timesinceload="+o)}ncbi.sg.getInstance()._sendAl(k.join("&"),null,e,h)}var n=window.onerror;window.onerror=function(d,e,h){if(!ncbi.sg.hasNotedErrorEvent){ncbi.sg.getInstance().noteEventData("jserror",{jserror:d,jserrorlocation:e,jserrorline:h,SELF_URL:window.location.href},["ncbi_sessionid","ncbi_phid"]);ncbi.sg.hasNotedErrorEvent=true;if(typeof n==="function")return n(d,e,h)}};
ncbi.sg._currentEventId=1;ncbi.sg.getEventId=function(){return ncbi.sg._currentEventId++};var m=[],v=[],F=[],x=false;ncbi.sg.sendElementEvent=function(d,e,h){f(d,e,h,false)};ncbi.sg.clickTimers=[];setClickEvent=function(){function d(){a()}var e=function(j){return(j=typeof j.parentNode!=="undefined"?j.parentNode:null)?o(j)?j:e(j):false},h=function(j){var q=j.target||j.srcElement;if(typeof q=="undefined"||q==null)return null;if(q.nodeType==3)q=j.target.parentNode;o(q)||(q=e(q));return q},k=function(j){return ncbi.sg.getInstance().isInLinkObjs(j)},
o=function(j){var q=typeof j.tagName!=="undefined"?j.tagName.toLowerCase():null,w=false,z=false;if(typeof jQuery!=="undefined")w=jQuery(j).is("button, input[type=button], input[type=submit], input[type=reset]");else if(q==="input"){w=j.type;w=w=="button"||w=="submit"||w=="reset"}else w=q==="button"?true:false;w||(z=q=="a"||q=="area");return z?"link":w?"button":k(j)?"linkObjs":null},l=function(j,q,w,z){function D(A){var G;if(A=A.parentNode)for(;A!==document;){if(G=A.dataset.section)break;A=A.parentNode}return G||
null}if(!(z&&z=="click"&&j.which&&j.which==3))if(!(!q||o(q)==null)){ncbi.sg.getInstance().setCookie("ncbi_prevPHID",ncbi.sg.getInstance().currentPageHitId);j=g(j);j.iscontextmenu=z=="contextmenu"?"true":"false";j={evt:j,link:q,tstamp:(new Date).getTime(),floodTstamp:(new Date).getTime()};b(j);ncbi.sg.clickTimers&&window.clearTimeout(ncbi.sg.clickTimers);ncbi.sg.clickTimers=window.setTimeout(function(){ncbi.sg.clickTimers=null},300);if(H&&z!="contextmenu"){q=D(q);ncbi_global_ga("send","event","internal link",
"click",q);ncbi.sg.gaPingsFired.push({event:"click",category:"internal link",label:q})}}};if(window.addEventListener){window.addEventListener("click",function(j){l(j,h(j),[],"click")});window.addEventListener("contextmenu",function(j){l(j,h(j),[],"contextmenu")},false);window.addEventListener("beforeunload",d)}else if(window.attachEvent){document.attachEvent("onclick",function(j){l(j,h(j),[],"click")});document.attachEvent("oncontextmenu",function(j){l(j,h(j),[],"contextmenu")},false);document.attachEvent("onbeforeunload",
d)}if(Event.prototype.stopPropagation){var s=Event.prototype.stopPropagation;Event.prototype.stopPropagation=function(){var j=h(this);if(o(j)!=null)if(this.type=="click")l(this,j,[],"click");else this.type=="contextmenu"&&l(this,j,[],"contextmenu");return s.apply(this,arguments)}}};ncbi.sg.isClickingEnabled&&setClickEvent();ncbi.sg.scanLinks=function(d){var e=ncbi.sg.getInstance();if(d){var h=typeof jQuery!=="undefined"&&jQuery?d instanceof jQuery:false;if(typeof d==="object"&&!(d instanceof Array)&&
!h)d=[d];e.addLinkObjs(d)}};ncbi.sg._ping=function(d,e,h,k,o){if(typeof o==="undefined"||o===null)o=true;typeof d==="undefined"||d===null||(typeof d==="object"&&d.nodeName!==undefined?i(d,e,h,k,o):p(d,e,o))};ncbi.sg.ping=function(d,e,h,k){ncbi.sg._ping(d,e,h,k,false)};ncbi.sg.loadTime=new Date;ncbi.sg.gaPingsFired=[];ncbi.sg.pingsFired=[];ncbi.sg.pingsSucceeded=[];ncbi.sg.prevPingsFired=null;ncbi.sg.prevPingsSucceeded=null;ncbi.sg.outstandingPings=0;ncbi.sg._isGBPage=false;ncbi.sg._urls={getDataObj:function(d){if(typeof d===
"string"||typeof DOMString!=="undefined"&&d instanceof DOMString||typeof String!=="undefined"&&d instanceof String){var e={};d=d.split("&");for(var h=0;h<d.length;h++)if(d[h].length){var k=d[h].split("="),o=k[0],l="";if(k.length==1)l="";else{l=k[1];if(k.length>2)for(var s=2;s<k.length;s++)l+="="+k[s]}e[o]=l}return e}else return false},getUrlParts:function(d){if(typeof d!=="undefined"&&d){d=d.split("?");if(d.length<=2)return d;else{for(var e=d[1],h=2;h<d.length;h++)e+="?"+d[h];return[d[0],e]}}return""},
getQueryString:function(d){d=this.getUrlParts(d);return d.length>1?typeof d[1]!=="undefined"&&d[1]?d[1]:"":null},getMainUrlPart:function(d){d=this.getUrlParts(d);return d.length>0?typeof d[0]!=="undefined"&&d[0]?d[0]:"":""},hasQuestionMark:function(d){return d.search(/\?/)!==-1},getDataStr:function(d){if(typeof d==="object"&&!(d instanceof Array)){var e=[];for(var h in d)e.push(h+"="+d[h]);return e.join("&")}else return false},attrInStr:function(d,e){if(typeof e!=="undefined"&&e&&e.length>0)if(typeof this.getDataObj(e)[d]!==
"undefined")return true;return false},attrInUrl:function(d,e){return this.attrInStr(this.getQueryString(e))},getAttrFromData:function(d,e){if(typeof e!=="undefined")return e[d]},getAttrFromStr:function(d,e){return this.getAttrFromData(d,this.getDataObj(e))},addAttr:function(d,e,h){h[d]=e;return h},addAttrToStr:function(d,e,h){h=this.getDataObj(h);h=this.addAttr(d,e,h);return this.getDataStr(h)},addDataToStr:function(d,e){e=e;for(var h in d)e=this.addAttrToStr(h,d[h],e);return e},addDataToObj:function(d,
e){for(var h in e)d[h]=e[h]},addAttrWithIndex:function(d,e,h){var k=ncbi.sg.getInstance();if(typeof d==="undefined"||!d)return e;if(typeof e!=="undefined"&&e){k=k.getVal(d);e[d]=k?k:"unknown";if(typeof h!=="undefined"&&h)e[d]+=".0"+ncbi.sg._ajaxRequestIndex}return e},addAttrWithIndexToUrl:function(d,e,h){var k=this.getMainUrlPart(e);e=this.getQueryString(e);e=e!==null?e:"";e=this.addAttrWithIndexToStr(d,e,h);return k+"?"+e},addAttrWithIndexToStr:function(d,e,h){e=this.getDataObj(e);ncbi.sg.getInstance();
e=this.addAttrWithIndex(d,e,h);return this.getDataStr(e)}}})();if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,b){var c=this.length>>>0;b=Number(b)||0;b=b<0?Math.ceil(b):Math.floor(b);if(b<0)b+=c;for(;b<c;b++)if(b in this&&this[b]===a)return b;return-1};(function(){function a(){ncbi_onloadTime=new Date}ncbi_onloadTime=null;if(typeof jQuery!=="undefined")jQuery(window).load(a);else{var b=window.onload;window.onload=function(c){b&&b(c);a()}}})();(function(){ncbi.sg._ajaxRequestIndex=
1;if(typeof XMLHttpRequest!=="undefined"){var a,b=function(f,g,i,p){if(typeof a==="undefined"||!a)a=ncbi.sg.getInstance();g=(g=a.getVal(g))?g:"unknown";if(typeof p!=="undefined"&&p)g+=".0"+ncbi.sg._ajaxRequestIndex;f.setRequestHeader(i,g)},c=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(){var f;if(typeof this._ncbi_skipOverride!=="undefined"&&this._ncbi_skipOverride)f=c.apply(this,arguments);else{f=arguments&&arguments.length>1&&typeof arguments[1]!=="undefined"?arguments[1]:
null;if(f!==null&&ncbi.sg._isGBPage){f=ncbi.sg._urls.addAttrWithIndexToUrl("ncbi_phid",f,true);f=ncbi.sg._urls.addAttrWithIndexToUrl("ncbi_sessionid",f);arguments[1]=f}f=c.apply(this,arguments);b(this,"ncbi_phid","NCBI-PHID",true);ncbi.sg._ajaxRequestIndex+=1}return f}}})();var u=["log","debug","info","warn","error","assert","dir","dirxml","group","groupEnd","time","timeEnd","count","trace","profile","profileEnd"];if(typeof console==="undefined"||typeof console==="function")console={};for(var K=0;K<
u.length;++K)if(typeof console[u[K]]==="undefined")console[u[K]]=function(){return false};ncbi.sg.getInstance().init();var H=false;var B=(u=ncbi.sg.getInstance()._cachedVals.ncbi_app)&&u.value;var C=(u=ncbi.sg.getInstance()._cachedVals.ncbi_db)&&u.value;var E=(u=ncbi.sg.getInstance()._cachedVals.ncbi_pdid)&&u.value;if(B&&C&&B=="entrez"&&(C=="nuccore"||C=="protein"))H=true;else if(B&&E&&B=="guide"&&E=="HomePage")H=true;else if(B&&B=="guide4beta"){E=(u=ncbi.sg.getInstance()._cachedVals.ncbi_page_type)&&
u.value;C=(u=ncbi.sg.getInstance()._cachedVals.ncbi_page_name)&&u.value;H=true}if(H){window.GoogleAnalyticsObject="ncbi_global_ga";u=document.createElement("script");u.setAttribute("src","//www.google-analytics.com/analytics.js");u.onload=function(){ncbi_global_ga("create","UA-68648221-3","auto");ncbi_global_ga("set","dimension1",B);C&&ncbi_global_ga("set","dimension2",C);E&&ncbi_global_ga("set","dimension3",E);ncbi_global_ga("send","pageview");var a={event:"pageview",cd1:B};if(C)a.cd2=C;if(E)a.cd3=
E;ncbi.sg.gaPingsFired.push(a)};document.getElementsByTagName("body")[0].appendChild(u)}}})();
